version: 1
builder:
  configs:
    - platform: ios
      scheme: SwiftUINavigationTransitions
      documentation_targets: [SwiftUINavigationTransitions]
      custom_documentation_parameters: [--include-extended-types]
    - platform: tvos
      scheme: SwiftUINavigationTransitions
