version: 1
builder:
  configs:
  - platform: ios
    scheme: NavigationTransitions
    documentation_targets: [NavigationTransitions]
    custom_documentation_parameters: [--include-extended-types]
  - platform: tvos
    scheme: NavigationTransitions
