version: 1
builder:
  configs:
    - platform: ios
      scheme: SwiftUINavigationTransitions
      documentation_targets: [SwiftUINavigationTransitions]
    - platform: tvos
      scheme: SwiftUINavigationTransitions
