version: 1
builder:
  configs:
  - platform: ios
    scheme: NavigationTransitions
    documentation_targets: [NavigationTransitions]
  - platform: macos-xcodebuild
    scheme: NavigationTransitions
  - platform: tvos
    scheme: NavigationTransitions
  - platform: watchos
    scheme: NavigationTransitions
