name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: swiftformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Format
        run: swiftformat .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run SwiftFormat
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
