name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: swiftformat
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: swiftformat .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run SwiftFormat
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
